# Generated by Django 4.0.5 on 2022-06-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_transactions_trx_trc20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=250, unique=True)),
                ('value', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='All_transactions_usdt_trc20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=250, unique=True)),
                ('value', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_type', models.CharField(max_length=250)),
                ('proxy_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('telegram_username', models.CharField(max_length=250)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('balance', models.FloatField(max_length=12)),
            ],
        ),
    ]
